# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py313"
line-length = 140
fix = true

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "TRY003", # Avoid specifying long messages outside the exception class
    "EM102", # Exception must not use an f-string literal, assign to variable first

    # May conflict with the formatter, https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "D203", # no-blank-line-before-class
    "D212", # multi-line-summary-first-line
    "E501",
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q",
    "COM812",
    "COM819",
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25

[lint.per-file-ignores]
"tests/**/*" = [
    "S101",  # use of assert is valid for testing
    "ANN001",  # no need for type annotations on all fixtures
    "ARG001",  # tests may declare fixtures as "unused" args
    "ANN201",  # tests don't need return annotations
    "INP001",  # tests don't need to be a package/namespace
    "S106",  # tests may contain hardcoded fake passwords
    "D103",  # tests don't need docstrings everywhere
]
"scripts/**/*" = [
    "S101",
    "ANN201",
    "INP001",
    "T201",
    "PLR1722",
]
